cine_livre_homepage:
    path:     /hello/{name}
    defaults: { _controller: CineLivreBundle:Default:index }
categ_livre:
    path:     /categ
    defaults: { _controller: CineLivreBundle:Categ:index }
categ2:
    path:     /categ2
    defaults: { _controller: CineLivreBundle:Categ:index2 }
auteur_liste:
    path:     /liste
    defaults: { _controller: CineLivreBundle:Auteur:list }
auteur_update:
    path:     /update
    defaults: { _controller: CineLivreBundle:Auteur:update }
editeur:
    path:     /editeur
    defaults: { _controller: CineLivreBundle:Editeur:index }
editeur_ajout:
    path:     /editeur/ajout
    defaults: { _controller: CineLivreBundle:Editeur:ajouter }
editeur_liste:
    path:     /editeur/liste
    defaults: { _controller: CineLivreBundle:Editeur:afficher }