<?php

namespace Cine\LivreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AuteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuteurRepository extends EntityRepository
{
    public function getAuteurs()
    {
       /* Création de la requète avec le query builder */
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select("a")
                     ->from("CineLivreBundle:Auteur", "a");

       /* On retourne les enregistrements */
        return $queryBuilder->getQuery()->getResult();
    }
}

?>